### ISSUE TITLE
Fine-tuning export of recalcitrant ORCID

### ISSUE THREAD

**Issue by Archilegt** [MrPike/orcid-to-bibtex#2] opened 2022-11-22 10:00 UTC
Dear @MrPike, thank you for this tool! I wonder when ORCID will make BibTex downloads available to everyone. They definitely have the capacity but not the interest.
 Fine-tuning the export:
@GrazingScientist detected a recalcitrant ID which is not producing the expected result:
https://orcid.org/0000-0003-3466-5038
Could this be fixed?

**Comment by GrazingScientist** [comment] 2022-11-22 14:03
What @Archilegt is referencing, is that the returned list only contains 1 BibTeX entry, although the publication list of the referenced ORCID member is by far longer. We have expected that the script would return all publications.

However, it seems that due to [filtering for "bibtex" formatted citations](https://github.com/MrPike/orcid-to-bibtex/blob/a5a965c52b071b19698e973af77faa7a6e474d72/orcid-to-bibtex.py#L52) many publications are sorted out.

Do you have an idea why ORCID is not returning proper data?

**Comment by MrPike** [comment] 2022-11-23 05:45
Thanks @Archilegt and @GrazingScientist for raising this. I'm sorry, but I'm currently very busy. I will try to find time to look into this issue over the weekend. 

One suspicion I have is that items are being filtered out because they are missing required attributes (on ORCID) in order to be valid BibTeX. This could be why ORCID is not returning BibTeX for these entries: it can't make valid BibTeX with the details provided. It's just a thought, I haven't investigated yet.

**Comment by MrPike** [comment] 2022-11-27 05:52
I had a chance to look at the responses we're getting from ORCID for the "recalcitrant ID" mentioned here. I can confirm that ORCID is not returning the expected “bibtex” citation-type, instead returning “formatted-unspecified”. What's strange is that, in most cases, the fields needed to make a BibTeX entry are in the JSON that is returned, but BibTeX is not being returned.

I've introduced additional safeguards with [abcad98](https://github.com/MrPike/orcid-to-bibtex/commit/abcad982b4975c0264c55a0266b55082f1b7806f) to ensure that the tool runs without error when encountering these unexpected citation-types. 

It is possible that in the future, _orcid-to-bibtex_ will be able to generate BibTeX entries from the available information. Before I add this, I would like to better understand how widespread this issue is. You are welcome to report your experience of this issue, via this thread.

**Comment by GrazingScientist** [comment] 2022-12-02 11:43
Thank you for your feedback, @MrPike . @Archilegt is more in need of this tool, so he could give more insights.

**Comment by MrPike** [comment] 2024-04-20 07:18
This issue may have been addressed in the most recent commit - assuming the entry has a DOI specified. Closing this issue for now, but happy to revisit if there's room for improving support for this.

**Closed as completed by MrPike** 2024-04-20 07:18 UTC
